# -*- coding: utf-8 -*-
"""Jauge

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sLPS9QuB1Uso9HaT-7f2IsCNtgroeEfE
"""

import matplotlib.pyplot as plt
import matplotlib.patches as patches
import numpy as np

def jauge(ax, valeur, valeur_max=100):
  """
  Dessine une jauge sur l'axe donné.

  Args:
    ax: L'axe Matplotlib sur lequel dessiner la jauge.
    valeur: La valeur à afficher sur la jauge.
    valeur_max: La valeur maximale de la jauge.
  """
  # Dessiner le fond de la jauge
  ax.add_patch(patches.Circle((0.5, 0.5), 0.4, fill=False, edgecolor='black', linewidth=2))

  # Calculer l'angle de l'arc
  angle = (valeur / valeur_max) * 180

  # Dessiner l'arc
  ax.add_patch(patches.Wedge((0.5, 0.5), 0.4, 180 - angle, 180, facecolor='blue'))

  # Dessiner l'aiguille
  angle_rad = np.radians(180 - angle)
  x = 0.5 + 0.35 * np.cos(angle_rad)
  y = 0.5 + 0.35 * np.sin(angle_rad)
  ax.plot([0.5, x], [0.5, y], color='red', linewidth=2)

  # Ajouter le texte
  ax.text(0.5, 0.5, f'{valeur:.0f}', ha='center', va='center', fontsize=12)

# Créer la figure et l'axe
fig, ax = plt.subplots()

# Dessiner la jauge
jauge(ax, 60)

# Masquer les axes
ax.set_axis_off()

# Afficher la jauge
plt.show()

import plotly.graph_objects as go

fig = go.Figure(go.Indicator(
    mode = "gauge+number",
    value = 90,
    domain = {'x': [0, 1], 'y': [0, 1]},
    title = {'text': "Jauge Plotly"},
    gauge = {'axis': {'range': [None, 100]}}
))

fig.show()